// ATPT holonomic solver -- root_pair.hpp port correctness.
//
//   1. eo_residuals / eo_jacobian / root_pair_dR vs the Python reference
//      (evidence/holonomic/root_pair_ref.tsv, generated by
//      scratchpad/gen_root_pair_ref.py from holonomic_ref/root_pair.py).
//   2. boundary_quartic_dR vs a central finite difference of
//      boundary_quartic over the bench cases.
//   3. (m,v) radial transport smoke test: cold-solve the quartic at the
//      lower end of an image band, transport the root pair to the upper end
//      with an RK4 + Newton corrector, and check the transported endpoints
//      against a cold quartic solve at every step -- reporting drift and how
//      often the tangency guard fails closed.
//
// Build (isolated):
//   cmake --build build-holonomic-m7 --target test_root_pair
//   ./build-holonomic-m7/test_root_pair \
//       evidence/holonomic/root_pair_ref.tsv /tmp/bench_cases.tsv

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "lcbinint/magnification/holonomic/boundary_polynomial.hpp"
#include "lcbinint/magnification/holonomic/cells.hpp"
#include "lcbinint/magnification/holonomic/lens_frame.hpp"
#include "lcbinint/magnification/holonomic/phi.hpp"
#include "lcbinint/magnification/holonomic/poly_roots.hpp"
#include "lcbinint/magnification/holonomic/radius_terms.hpp"
#include "lcbinint/magnification/holonomic/root_pair.hpp"

using namespace lcbinint::holonomic;

namespace {

int g_fail = 0, g_checks = 0;
double g_worst = 0.0;

void chk(const char* what, double got, double want, double atol, double rtol) {
    ++g_checks;
    const double d = std::fabs(got - want);
    const double tol = atol + rtol * std::fabs(want);
    if (std::fabs(want) > 1e-9) g_worst = std::max(g_worst, d / std::fabs(want));
    if (d > tol) {
        ++g_fail;
        std::fprintf(stderr, "  FAIL %-26s got=% .16g want=% .16g |d|=%.3e\n",
                     what, got, want, d);
    }
}

std::vector<double> real_roots_desc(const std::array<double, 5>& pc) {
    double c[5];
    int deg = quartic_descending(pc, c);
    if (deg <= 0) return {};
    auto z = aberth<double>(c, deg, 60);
    std::vector<double> r;
    for (auto& zz : z)
        if (std::fabs(zz.im) <= 1e-8 * (1.0 + std::fabs(zz.re)))
            r.push_back(zz.re);
    std::sort(r.begin(), r.end());
    return r;
}

// ---- 1. reference parity --------------------------------------------------
void test_reference(const std::string& path) {
    std::ifstream in(path);
    if (!in) {
        std::fprintf(stderr, "cannot open %s\n", path.c_str());
        ++g_fail;
        return;
    }
    std::string line;
    long n = 0;
    while (std::getline(in, line)) {
        std::istringstream ls(line);
        std::string name;
        double R, pc[5], pcR[5], m, v, E, O, Em, Ev, Om, Ov, dm, dv;
        int ok;
        ls >> name >> R;
        for (double& x : pc) ls >> x;
        for (double& x : pcR) ls >> x;
        ls >> m >> v >> E >> O >> Em >> Ev >> Om >> Ov >> dm >> dv >> ok;
        if (!ls) continue;
        ++n;

        std::array<double, 5> a_pc{pc[0], pc[1], pc[2], pc[3], pc[4]};
        std::array<double, 5> a_pcR{pcR[0], pcR[1], pcR[2], pcR[3], pcR[4]};
        RootPair rp{m, v};

        // E, O are root-solve residuals -- "should be ~0", carrying the
        // Python np.roots noise (~1e-10).  Check the port reproduces the
        // reference to that noise floor, not to a relative tolerance.
        EO eo = eo_residuals(rp, a_pc);
        chk("E", eo.E, E, 5e-9, 1e-6);
        chk("O", eo.O, O, 5e-9, 1e-6);

        EOJac J = eo_jacobian(rp, a_pc);
        chk("E_m", J.E_m, Em, 1e-11, 1e-10);
        chk("E_v", J.E_v, Ev, 1e-11, 1e-10);
        chk("O_m", J.O_m, Om, 1e-11, 1e-10);
        chk("O_v", J.O_v, Ov, 1e-11, 1e-10);

        RootPairDR d = root_pair_dR(rp, a_pc, a_pcR);
        ++g_checks;
        if ((int)d.ok != ok) {
            ++g_fail;
            std::fprintf(stderr, "  FAIL root_pair_dR ok got=%d want=%d\n",
                         (int)d.ok, ok);
        }
        if (ok) {
            chk("dm/dR", d.dm_dR, dm, 1e-9, 1e-8);
            chk("dv/dR", d.dv_dR, dv, 1e-9, 1e-8);
        }
    }
    std::fprintf(stderr, "  [1] reference rows checked: %ld\n", n);
}

// ---- 2. boundary_quartic_dR vs central FD --------------------------------
void test_dR_fd(const std::string& bench) {
    std::ifstream in(bench);
    std::string line;
    long n = 0;
    double worst = 0.0;
    while (std::getline(in, line)) {
        std::istringstream ls(line);
        double xs, ys, rho, q, a, bary, u, tj;
        std::string name;
        if (!(ls >> xs >> ys >> rho >> q >> a >> bary >> u >> tj >> name))
            continue;
        LensParams p{xs, ys, rho, q, a, (bool)bary};
        PrimaryFrame pf = PrimaryFrame::from(p);
        for (double R : {0.3, 0.55, 0.8, 1.0 + a * 0.7}) {
            const double h = 1e-6 * std::max(R, 1.0);
            QuarticCoeffs plus = boundary_quartic(R + h, pf);
            QuarticCoeffs minus = boundary_quartic(R - h, pf);
            QuarticCoeffs an = boundary_quartic_dR(R, pf);
            for (int i = 0; i < 5; ++i) {
                double fd = (plus.p[i] - minus.p[i]) / (2.0 * h);
                double sc = std::fabs(an.p[i]) + std::fabs(fd) + 1e-9;
                worst = std::max(worst, std::fabs(fd - an.p[i]) / sc);
                ++g_checks;
                if (std::fabs(fd - an.p[i]) > 1e-6 * sc + 1e-9) {
                    ++g_fail;
                    std::fprintf(stderr,
                                 "  FAIL dR FD %s R=%.3f i=%d an=% .8g fd=% .8g\n",
                                 name.c_str(), R, i, an.p[i], fd);
                }
            }
            ++n;
        }
    }
    std::fprintf(stderr, "  [2] dR FD samples: %ld, worst rel %.2e\n", n, worst);
}

// ---- 3. (m,v) transport smoke test -------------------------------------
// One RK4 step of (dm/dR, dv/dR) then one Newton correction on (E,O)=0.
bool transport_step(RootPair& rp, double R, double dR, const PrimaryFrame& pf) {
    auto deriv = [&](const RootPair& s, double r, double& dm, double& dv) {
        RootPairDR d = root_pair_dR(s, r, pf);
        dm = d.dm_dR;
        dv = d.dv_dR;
        return d.ok;
    };
    double k1m, k1v, k2m, k2v, k3m, k3v, k4m, k4v;
    if (!deriv(rp, R, k1m, k1v)) return false;
    RootPair s2{rp.m + 0.5 * dR * k1m, rp.v + 0.5 * dR * k1v};
    if (!deriv(s2, R + 0.5 * dR, k2m, k2v)) return false;
    RootPair s3{rp.m + 0.5 * dR * k2m, rp.v + 0.5 * dR * k2v};
    if (!deriv(s3, R + 0.5 * dR, k3m, k3v)) return false;
    RootPair s4{rp.m + dR * k3m, rp.v + dR * k3v};
    if (!deriv(s4, R + dR, k4m, k4v)) return false;
    rp.m += dR / 6.0 * (k1m + 2 * k2m + 2 * k3m + k4m);
    rp.v += dR / 6.0 * (k1v + 2 * k2v + 2 * k3v + k4v);

    // Newton polish on (E,O)=0 at R+dR (2x2, a couple of iterations).
    QuarticCoeffs pc = boundary_quartic(R + dR, pf);
    double scale = 0.0;
    for (double c : pc.p) scale = std::max(scale, std::fabs(c));
    for (int it = 0; it < 5; ++it) {
        EO eo = eo_residuals(rp, pc.p);
        EOJac J = eo_jacobian(rp, pc.p);
        double det = J.E_m * J.O_v - J.E_v * J.O_m;
        if (std::fabs(det) < 1e-14) return false;
        double ddm = -(J.O_v * eo.E - J.E_v * eo.O) / det;
        double ddv = -(-J.O_m * eo.E + J.E_m * eo.O) / det;
        rp.m += ddm;
        rp.v += ddv;
        if (std::fabs(ddm) + std::fabs(ddv) < 1e-15) break;
    }
    EO eof = eo_residuals(rp, pc.p);
    // Fail closed: not converged, tangency (v -> 0), or non-finite.  A tiny
    // v means the two real roots are colliding -- exactly the near-tangency
    // that radius_terms already flags GRADIENT_UNRELIABLE.
    if (!std::isfinite(rp.m) || !std::isfinite(rp.v)) return false;
    if (std::fabs(eof.E) + std::fabs(eof.O) > 1e-9 * (scale + 1.0)) return false;
    if (rp.v < 1e-10) return false;
    return true;
}

void test_transport(const std::string& bench) {
    std::ifstream in(bench);
    std::string line;
    long bands = 0, transported = 0, failed_closed = 0;
    double worst_end = 0.0;
    std::string worst_ctx;
    const int STEPS = 63;  // 64 nodes -> 63 intervals, like the cell integrator
    while (std::getline(in, line)) {
        std::istringstream ls(line);
        double xs, ys, rho, q, a, bary, u, tj;
        std::string name;
        if (!(ls >> xs >> ys >> rho >> q >> a >> bary >> u >> tj >> name))
            continue;
        LensParams p{xs, ys, rho, q, a, (bool)bary};
        PrimaryFrame pf = PrimaryFrame::from(p);

        TopologyResult topo = classify_cells(pf);
        for (const auto& c : topo.cells) {
            if (c.kind != ArcKind::kArcs) continue;
            double w = c.r_hi - c.r_lo;
            if (w < 1e-7) continue;
            double lo = c.r_lo + 1e-6 * w, hi = c.r_hi - 1e-6 * w;

            // cold arcs at lo
            QuarticCoeffs q0 = boundary_quartic(lo, pf);
            auto rr = real_roots_desc(q0.p);
            if (rr.size() < 2) continue;
            // one representative arc: the pair with positive-phi midpoint
            int chosen = -1;
            for (size_t i = 0; i + 1 < rr.size(); ++i) {
                double tm = 0.5 * (rr[i] + rr[i + 1]);
                double thm = 2.0 * std::atan(tm);
                if (phi_lens(lo, thm, pf) > 0.0) {
                    chosen = (int)i;
                    break;
                }
            }
            if (chosen < 0) continue;
            ++bands;
            RootPair rp = root_pair_from_endpoints(rr[chosen], rr[chosen + 1]);

            bool alive = true, guard_miss = false;
            double this_worst = 0.0;
            const double dR = (hi - lo) / STEPS;
            for (int s = 0; s < STEPS && alive; ++s) {
                double R = lo + s * dR;
                if (!transport_step(rp, R, dR, pf)) {
                    alive = false;
                    break;
                }
                double Rn = R + dR;
                QuarticCoeffs qn = boundary_quartic(Rn, pf);
                auto rn = real_roots_desc(qn.p);
                if (rn.size() < 2) {
                    // the real arc has closed but the guard let transport
                    // continue -- that would be a silent topology error
                    guard_miss = true;
                    alive = false;
                    break;
                }
                double best_lo = 1e9, best_hi = 1e9;
                for (double x : rn) {
                    best_lo = std::min(best_lo, std::fabs(x - rp.t_minus()));
                    best_hi = std::min(best_hi, std::fabs(x - rp.t_plus()));
                }
                this_worst = std::max({this_worst, best_lo, best_hi});
            }
            if (guard_miss) {
                ++g_fail;
                std::fprintf(stderr,
                             "  FAIL guard miss: %s cell [%.4f,%.4f] arc "
                             "closed, transport still alive\n",
                             name.c_str(), lo, hi);
            }
            if (alive) {
                ++transported;
                if (this_worst > worst_end) {
                    worst_end = this_worst;
                    char b[128];
                    std::snprintf(b, sizeof b, "%s cell [%.4f,%.4f] w=%.4f",
                                  name.c_str(), lo, hi, hi - lo);
                    worst_ctx = b;
                }
            } else {
                ++failed_closed;
            }
        }
    }
    std::fprintf(stderr,
                 "  [3] bands %ld -> transported %ld (worst endpoint drift "
                 "%.2e @ %s), failed closed %ld\n",
                 bands, transported, worst_end, worst_ctx.c_str(),
                 failed_closed);
    // When transport completes a band without tripping the guard, the
    // transported endpoints must land inside the downstream polish basin.
    // radius_terms only *seeds* polish_endpoint (6 Newton iters on the true
    // phi) with these -- "arc seeds, not final endpoints" -- so anything
    // below ~1e-3 in t is fully absorbed.  Observed worst is ~1e-5 (near
    // tangencies, where the cold reference Aberth is itself noisy).
    if (transported > 0 && worst_end > 1e-3) {
        ++g_fail;
        std::fprintf(stderr,
                     "  FAIL transport endpoints drifted %.2e > 1e-3 "
                     "(outside polish basin) @ %s\n",
                     worst_end, worst_ctx.c_str());
    }
    ++g_checks;
}

}  // namespace

int main(int argc, char** argv) {
    const std::string ref =
        argc > 1 ? argv[1] : std::string("evidence/holonomic/root_pair_ref.tsv");
    const std::string bench =
        argc > 2 ? argv[2] : std::string("/tmp/bench_cases.tsv");

    test_reference(ref);
    test_dR_fd(bench);
    test_transport(bench);

    std::fprintf(stderr, "\n%d checks, %d failures, worst rel %.2e\n", g_checks,
                 g_fail, g_worst);
    return g_fail == 0 ? 0 : 1;
}
